import React from 'react'
import styles from '/styles/Home.module.css'

import NewsBody from '../../components/news/NewsBody'
import NewsHeader from '../../components/news/NewsHeader'
export default function news() {
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>salextra Limited</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main className={styles.main}>
      <NewsHeader />
    <NewsBody />
      </main>

    </div>  
  )
}
