import React from "react";
import styles from '/styles/Home.module.css'
import CareerBody from "../../components/career/CareerBody";
import CareerHeader from "../../components/career/CareerHeader";
import JobSection from "../../components/career/JobSection";

export default function index() {
  return (
    <div className={styles.container}>
      {/* <Head>
      <title>salextra Limited</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head> */}

      <main className={styles.main}>
        <CareerHeader />
        <CareerBody />
        <JobSection />
      </main>
    </div>
  );
}
