import React from 'react'
import Image from 'next/image'
import Head from 'next/head'
import styles from '/styles/Home.module.css'
import HeaderBanner from '/components/aboutUs/HeaderBanner'
import AboutusBody from '/components/aboutUs/AboutusBody'
import Team from '/components/aboutUs/Team'

export default function AboutUsPage() {
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>salextra Limited</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main className={styles.main}>
        <HeaderBanner  />
        <AboutusBody/>
        <Team />
      </main>

    </div>
  )
}
