import React from 'react'
import Motorola from '../../components/business/Motorola'
import styles from '/styles/Home.module.css'

export default function motorola() {
  return (
    <div className={styles.container}>
      {/* <Head>
      <title>salextra Limited</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head> */}

      <main className={styles.main}>
        <Motorola />
      </main>
    </div>
  )
}
